import { createClient } from "@libsql/client";

const url = process.env.TURSO_DATABASE_URL;
const authToken = process.env.TURSO_AUTH_TOKEN;
if (!url || !authToken) throw new Error("TURSO_DATABASE_URL と TURSO_AUTH_TOKEN を設定してください");

const db = createClient({ url, authToken });
const statements = [
  `CREATE TABLE IF NOT EXISTS models (id TEXT PRIMARY KEY, name TEXT NOT NULL, version TEXT NOT NULL, description TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(name, version))`,
  `CREATE TABLE IF NOT EXISTS races (id TEXT PRIMARY KEY, race_date TEXT NOT NULL, venue TEXT NOT NULL, race_number INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'scheduled', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(race_date, venue, race_number))`,
  `CREATE TABLE IF NOT EXISTS predictions (id TEXT PRIMARY KEY, race_id TEXT NOT NULL REFERENCES races(id), model_id TEXT REFERENCES models(id), predicted_first INTEGER NOT NULL, predicted_second INTEGER NOT NULL, odds REAL, estimated_probability REAL, expected_value REAL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(race_id, model_id, predicted_first, predicted_second))`,
  `CREATE TABLE IF NOT EXISTS bets (id TEXT PRIMARY KEY, prediction_id TEXT NOT NULL REFERENCES predictions(id), bet_type TEXT NOT NULL, first_number INTEGER NOT NULL, second_number INTEGER NOT NULL, bet_amount INTEGER NOT NULL CHECK(bet_amount >= 0), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(prediction_id, bet_type, first_number, second_number))`,
  `CREATE TABLE IF NOT EXISTS race_results (id TEXT PRIMARY KEY, race_id TEXT NOT NULL UNIQUE REFERENCES races(id), first_number INTEGER NOT NULL, second_number INTEGER NOT NULL, payout INTEGER NOT NULL CHECK(payout >= 0), created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS simulation_results (id TEXT PRIMARY KEY, race_id TEXT NOT NULL REFERENCES races(id), prediction_id TEXT NOT NULL UNIQUE REFERENCES predictions(id), investment INTEGER NOT NULL, return_amount INTEGER NOT NULL, profit INTEGER NOT NULL, roi REAL, is_hit INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(race_id, prediction_id))`,
  `CREATE TABLE IF NOT EXISTS daily_results (id TEXT PRIMARY KEY, result_date TEXT NOT NULL UNIQUE, race_count INTEGER NOT NULL DEFAULT 0, bet_count INTEGER NOT NULL DEFAULT 0, investment INTEGER NOT NULL DEFAULT 0, return_amount INTEGER NOT NULL DEFAULT 0, profit INTEGER NOT NULL DEFAULT 0, roi REAL, status TEXT NOT NULL DEFAULT 'pending', error_message TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS experiments (id TEXT PRIMARY KEY, model_id TEXT NOT NULL REFERENCES models(id), name TEXT NOT NULL, investment INTEGER NOT NULL, return_amount INTEGER NOT NULL, profit INTEGER NOT NULL, roi REAL, race_count INTEGER NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS analysis_comments (id TEXT PRIMARY KEY, target_type TEXT NOT NULL CHECK(target_type IN ('daily_result','race_prediction','experiment')), target_id TEXT NOT NULL, comment TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(target_type, target_id))`,
  `CREATE TABLE IF NOT EXISTS suitability_condition_stats (id TEXT PRIMARY KEY, model_id TEXT NOT NULL REFERENCES models(id), condition_key TEXT NOT NULL, venue TEXT, field_size INTEGER, line_pattern TEXT, confidence_band TEXT, score_gap_band TEXT, odds_band TEXT, athlete_data_band TEXT, sample_count INTEGER NOT NULL, investment INTEGER NOT NULL, return_amount INTEGER NOT NULL, roi REAL, hit_rate REAL, data_cutoff_at TEXT NOT NULL, rule_version TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(model_id, condition_key, data_cutoff_at, rule_version))`,
  `CREATE TABLE IF NOT EXISTS prediction_suitability (id TEXT PRIMARY KEY, prediction_id TEXT NOT NULL UNIQUE REFERENCES predictions(id), grade TEXT NOT NULL CHECK(grade IN ('A','B','C','D')), similar_race_count INTEGER NOT NULL, historical_roi REAL NOT NULL, historical_hit_rate REAL NOT NULL, is_data_sufficient INTEGER NOT NULL DEFAULT 0, recommendation TEXT NOT NULL CHECK(recommendation IN ('buy','skip')), rule_version TEXT NOT NULL, feature_snapshot_json TEXT, data_cutoff_at TEXT NOT NULL, calculated_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, CHECK(data_cutoff_at <= calculated_at))`,
  `CREATE TABLE IF NOT EXISTS simulation_strategy_results (id TEXT PRIMARY KEY, simulation_result_id TEXT NOT NULL REFERENCES simulation_results(id), strategy_key TEXT NOT NULL CHECK(strategy_key IN ('all','suitability_a','suitability_ab')), decision TEXT NOT NULL CHECK(decision IN ('buy','skip')), hypothetical_investment INTEGER NOT NULL, hypothetical_return_amount INTEGER NOT NULL, strategy_investment INTEGER NOT NULL, strategy_return_amount INTEGER NOT NULL, is_hypothetical_hit INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(simulation_result_id, strategy_key))`,
  `CREATE TABLE IF NOT EXISTS daily_strategy_results (id TEXT PRIMARY KEY, result_date TEXT NOT NULL, strategy_key TEXT NOT NULL CHECK(strategy_key IN ('all','suitability_a','suitability_ab')), purchase_race_count INTEGER NOT NULL DEFAULT 0, skipped_race_count INTEGER NOT NULL DEFAULT 0, investment INTEGER NOT NULL DEFAULT 0, return_amount INTEGER NOT NULL DEFAULT 0, profit INTEGER NOT NULL DEFAULT 0, roi REAL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(result_date, strategy_key))`,
  `CREATE TABLE IF NOT EXISTS race_metadata (race_id TEXT PRIMARY KEY REFERENCES races(id), venue_code TEXT NOT NULL, grade TEXT, race_name TEXT, start_time TEXT, field_size INTEGER NOT NULL DEFAULT 0, source TEXT NOT NULL, collected_at TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS model_runs (model_id TEXT PRIMARY KEY REFERENCES models(id), data_cutoff_at TEXT NOT NULL, training_race_count INTEGER, validation_race_count INTEGER, feature_columns_json TEXT NOT NULL, artifact_checksum TEXT, source TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS data_sync_runs (id TEXT PRIMARY KEY, source TEXT NOT NULL, sync_type TEXT NOT NULL, target_date TEXT, status TEXT NOT NULL, item_count INTEGER NOT NULL DEFAULT 0, error_message TEXT, started_at TEXT NOT NULL, finished_at TEXT)`,
  `CREATE TABLE IF NOT EXISTS experiment_strategy_results (id TEXT PRIMARY KEY, experiment_id TEXT NOT NULL REFERENCES experiments(id), strategy_key TEXT NOT NULL CHECK(strategy_key IN ('all','suitability_a','suitability_ab')), purchase_race_count INTEGER NOT NULL, skipped_race_count INTEGER NOT NULL, investment INTEGER NOT NULL, return_amount INTEGER NOT NULL, profit INTEGER NOT NULL, roi REAL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE(experiment_id, strategy_key))`,
  `CREATE INDEX IF NOT EXISTS idx_races_date ON races(race_date)`,
  `CREATE INDEX IF NOT EXISTS idx_predictions_race ON predictions(race_id)`,
  `CREATE INDEX IF NOT EXISTS idx_comments_target ON analysis_comments(target_type, target_id)`,
  `CREATE INDEX IF NOT EXISTS idx_suitability_stats_lookup ON suitability_condition_stats(model_id, condition_key, data_cutoff_at)`,
  `CREATE INDEX IF NOT EXISTS idx_prediction_suitability_grade ON prediction_suitability(grade, is_data_sufficient)`,
  `CREATE INDEX IF NOT EXISTS idx_strategy_results_strategy ON simulation_strategy_results(strategy_key, decision)`,
  `CREATE INDEX IF NOT EXISTS idx_daily_strategy_date ON daily_strategy_results(result_date, strategy_key)`,
  `CREATE INDEX IF NOT EXISTS idx_race_metadata_source ON race_metadata(source, collected_at)`,
  `CREATE INDEX IF NOT EXISTS idx_experiment_strategy ON experiment_strategy_results(experiment_id, strategy_key)`,
];

await db.batch(statements.map((sql) => ({ sql, args: [] })), "write");
console.log(`競輪V1: ${statements.length}件のマイグレーションを適用しました`);
